// RobotBuilder Version: 1.5
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


#ifndef OI_H
#define OI_H

#include "WPILib.h"

class OI {
private:
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
	Joystick* buttonStick;
	JoystickButton* allFlat;
	JoystickButton* spinnerIn;
	JoystickButton* spinnerOut;
	JoystickButton* spinnerFastIn;
	JoystickButton* spinnerFastOut;
	JoystickButton* extendPiston;
	JoystickButton* retractPiston;
	JoystickButton* climbUp;
	JoystickButton* setupPistonButton;
	Joystick* driveStick;
	JoystickButton* slowMode;
	JoystickButton* fastMode;
	JoystickButton* fastLoader;



    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
public:
	OI();
 
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=PROTOTYPES

	Joystick* getdriveStick();
	Joystick* getbuttonStick();
	double GetLeftDriveThumbStick();
	double GetRightDriveThumbStick();
	double GetLoaderThumbStick();
	double GetClimberThumbStick();



    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=PROTOTYPES
};

#endif
