// RobotBuilder Version: 1.5
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.




#include "ClimberPneumatics.h"
#include "../RobotMap.h"
#include "WPILib.h"
// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=INCLUDES
// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=INCLUDES

ClimberPneumatics::ClimberPneumatics() : Subsystem("ClimberPneumatics") {
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
	extender = RobotMap::climberPneumaticsDoubleSolenoid2;
	retractor = RobotMap::climberPneumaticsDoubleSolenoid1;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
}
    
void ClimberPneumatics::InitDefaultCommand() {
	// Set the default command for a subsystem here.
	//SetDefaultCommand(new MySpecialCommand());
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND
}
//forward should give air to the piston
//reverse should let air out of the piston
void ClimberPneumatics::LowAir() {
	extender->Set(DoubleSolenoid::kReverse);
	retractor->Set(DoubleSolenoid::kReverse);
} //start match, piston should be retracted with low air so we let air out of the piston

void ClimberPneumatics::Extending() {
	extender->Set(DoubleSolenoid::kForward);
	retractor->Set(DoubleSolenoid::kReverse);
} //extend piston, back of the piston should have 30 psi so extender solenoid should give air while retractor solenoid is coded to release air in the front

void ClimberPneumatics::Retracting() {
	extender->Set(DoubleSolenoid::kReverse);
	retractor->Set(DoubleSolenoid::kForward);
} //retract piston, front of the piston should have 60 psi so retractor solenoid should give air while extender solenoid should release air from back of the piston

void ClimberPneumatics::Off() {
	extender->Set(DoubleSolenoid::kOff);
	retractor->Set(DoubleSolenoid::kOff);
} //piston is off so no air going in and/or out so both solenoids are both off
// Put methods for controlling this subsystem
// here. Call these from Commands.

