// RobotBuilder Version: 1.5
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.




#include "loaderSpin.h"
#include "../RobotMap.h"
#include "WPILib.h"
// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=INCLUDES
// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=INCLUDES

LoaderSpin::LoaderSpin() : Subsystem("loaderSpin") {
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
	spin = RobotMap::loaderSpinSpin;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
}
    
void LoaderSpin::InitDefaultCommand() {
	// Set the default command for a subsystem here.
	//SetDefaultCommand(new MySpecialCommand());
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND
}

void LoaderSpin::In() {
	spin->Set(0.5);
// Put methods for controlling this subsystem
// here. Call these from Commands.

}


void LoaderSpin::Out() {
	spin->Set(-0.5);

}

void LoaderSpin::Stop() {
	spin->Set(0);

}
void LoaderSpin::FastOut() {
	spin->Set(-1);

}

void LoaderSpin::FastIn() {
	spin->Set(1);

}
