// RobotBuilder Version: 1.5
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.



#include "WPILib.h"
#include "loaderAngle.h"
#include "../Commands/DefaultAngleLoader.h"// This fixes the cant find thing error
#include "../RobotMap.h"
#include "WPILib.h"
#include <math.h> // acos to find angle
#define PI 3.14159265
// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=INCLUDES
// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=INCLUDES

LoaderAngle::LoaderAngle() : Subsystem("loaderAngle") {
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
	angle = RobotMap::loaderAngleangle;
	angle2 = RobotMap::loaderAngleangle2;
	analogPotentiometer1 = RobotMap::loaderAngleAnalogPotentiometer1;
	ARMLENGTH = 1; //filler number.  need to change
	ARMEDGESPACE = 1;
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
}
    
void LoaderAngle::InitDefaultCommand() {
	// Set the default command for a subsystem here.
	//SetDefaultCommand(new MySpecialCommand());
	SetDefaultCommand(new DefaultAngleLoader());
}

void LoaderAngle::Move(float value) {
	angle->Set(value);
	angle2->Set(-value);//
}


void LoaderAngle::Stop() {
	angle->Set(0);
}

float LoaderAngle::GetAngle(){
	float stringLength = analogPotentiometer1->Get();// gets the length in inches
	//Finds angle of Potentiometer using Pythag Thm and Trig
	float angle = acos((( this->ARMLENGTH * ARMLENGTH + ARMEDGESPACE * ARMEDGESPACE - stringLength * stringLength)/(2 * ARMLENGTH * ARMEDGESPACE)) * (180.0 / PI));
	//returns the angle of the potentiometer.
	return angle;
}
// Put methods for controlling this subsystem
// here. Call these from Commands.

